[flang][tests] Fix Python bug in the lit config
Without this change LIT tests for Flang fail with:
```
TypeError: append() takes exactly one argument (2 given)
```

(cherry picked from commit cbb7f1420b747aae09a7f728c186bb0c2702eb02)